# Generated by Django 4.2.7 on 2024-01-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_generatorapp', '0002_registerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdata',
            name='pwd',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
